### ISSUE TITLE
Investigate enabling Corbetura

### ISSUE THREAD

**Issue by sfloess** [FlossWare/jCore#47]
For some reason when we instrument using Corbetura downstream projects (like [Keraia](https://github.com/solenopsis/Keraiai)) yield ClassNotFoundException's:
```
org.solenopsis.keraiai.credentials.AbstractCredentialsTest
test_getSecurityPassword_blankPassword(org.solenopsis.keraiai.credentials.AbstractCredentialsTest)  Time elapsed: 0.012 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalArgumentException> but was<java.lang.NoClassDefFoundError>
	at org.solenopsis.keraiai.credentials.AbstractCredentialsTest.test_getSecurityPassword_blankPassword(AbstractCredentialsTest.java:203)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector
	at org.solenopsis.keraiai.credentials.AbstractCredentialsTest.test_getSecurityPassword_blankPassword(AbstractCredentialsTest.java:203)
```
My initial suspicion is the configration/goal sections of the pom.xml.

This is related to [Keraiai issue 27](https://github.com/solenopsis/Keraiai/issues/27).

**Comment by sfloess** [comment]
Closing as the maven life cycle was doing corbetura on clean - this caused instrumentation at the wrong time.
